### ISSUE TITLE
Ability to get proto file from a descriptor

### ISSUE THREAD

**Issue by nikunjy** [elixir-protobuf/protobuf#220]
Protobuf libraries (native and thirdparty) support getting a proto file from a message descriptor in golang, python and java.  What would it take to support this in this protobuf compiler. 

Here is what it would look like 

sample.proto 
```
message Foo { 
  int a = 1;
}
``` 

sample.pb.ex 
``` 
defmodule Foo do:
  use Protobuf ....etc
   defstruct [ :a]
   field :a, 1
```
Now if I create  an object of `Foo` then I am looking to create an API `to_proto` such that 
``` 
foo = %Foo{}
foo.to_proto() => # gives the sample.proto stringified 
``` 

This will be a useful functionality to add because we use `kafkaex` and protobuf already. We are planning to use kafka schema registry and in order to use that we need this API.

**Comment by whatyouhide** [comment]
We don't get the source string as is from `protoc`. We get the "source code info" (`Google.Protobuf.SourceCodeInfo`) and we might be able to rebuild the original source from that, but it's not a trivial task. We can't easily just read the `.proto` files either because they can contain multiple or nested messages, so mapping from a single message to its Protobuf source string would not be possible (without parsing the `.proto` file).

Can you show some examples of the API for this in Python, Go, or Java? 🙃

**Comment by nikunjy** [comment]
Hey @whatyouhide  thank you so much for replying.  
For python when `.pb.py` files are generated they have this https://googleapis.dev/python/protobuf/latest/google/protobuf/descriptor.html#google.protobuf.descriptor.FileDescriptor  which has the `serialized_pb` field that has the proto 

Confluent has written a protobuf schema and serializer for protobuf here https://github.com/confluentinc/schema-registry/blob/master/protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java#L475
it used here https://github.com/confluentinc/schema-registry/blob/master/protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/AbstractKafkaProtobufSerializer.java

For Golang, the generate `pb.go` files have `protoreflect.FileDescriptor` and there exist packages like this https://github.com/jhump/protoreflect which can do nice things including converting a file descriptor to a `.proto` file 


I understand this is not a trivial task but I am unsure where to even get started to add support in this library. Any help you can provide is helpful, I will be open to contributing as well.

**Comment by whatyouhide** [comment]
@nikunjy ah, I see what the languages are doing. This is great! We already support retrieving the descriptor. All you have to do is generate your Elixir files with

```elixir
protoc --elixir_out=gen_descriptors=true:/path/to/output ...
```

Now, the generated Elixir modules will have a `descriptor/0` function that returns the descriptor (like `Google.Protobuf.DescriptorProto`) with the source code info.

So, you can write a library separate from this one that takes that descriptor and turn it into `.proto` (like what https://github.com/jhump/protoreflect is kind of doing, if I got that right).

Since this functionality is not core to how Protobuf is meant to be used, I think it's better if we don't include it in this library and add the maintenance overhead here, but instead keep it as a separate library. Hope all of this makes sense!

Thanks for the suggestion 🙃 💟
