### ISSUE TITLE
Protobuf.JSON.encode does not work with :use_proto_names option

### ISSUE THREAD

**Issue by alberthives** [elixir-protobuf/protobuf#244]
When I create a `.proto` file that has fields that have `_` characters and attempt to encode the Protobuf type into JSON like below it doesn't seem to be doing so.

```protobuf
string my_type = 1;
```

```elixir
Protobuf.JSON.encode(data, [:use_proto_names])
```

Expected JSON:

```json
{"my_type": "blah"}
```

Actual JSON:

```json
{"myType": "blah"}
```

The generated Elixir code sets the `json_name` to `"myType"`.

Is there a way to generate the Elixir code so that the `json_name` to `"my_type"`?

The workaround is to manually change `json_name` on each field.

**Comment by whatyouhide** [comment]
@alberthives thanks for the report!

The generated `json_name` will always be `myType` unless you change the `json_name` option **in the `.proto` file itself.

However, `:use_proto_names` should ignore the `json_name` option and just use the Protobuf field name instead.

You are using the option incorrectly though. You have to pass `use_proto_names: true | false`, not `[:use_proto_names]`.

This will likely fix your issue:

```elixir
Protobuf.JSON.encode(message, use_proto_names: true)
```

I pushed a commit (0c198ce) that improves option validation so that in the future you'll get an error if you pass invalid options.

**Comment by alberthives** [comment]
I can confirm that this fixes the issue. Thanks @whatyouhide
