### ISSUE TITLE
Generated code appears to be changed via "mix format"

### ISSUE THREAD

**Issue by thbar** [elixir-protobuf/protobuf#278]
First, thanks for your maintenance of `protobuf`! We use it at https://transport.data.gouv.fr/ to decode GTFS-RT (realtime transportation) files (to interpret the data here https://transport.data.gouv.fr/resources/79317?locale=en or even to show realtime vehicle positions at https://transport.data.gouv.fr/explore), and are very happy to see it maintained properly!

While bumping up `protobuf` to the latest version, I regenerated the `.ex` files with `protoc --elixir_out=. gtfs-realtime.proto`.

I noticed that our build failed afterwards due to `mix format --check-formatted --dry-run`, because the generated files are not formatted as expected.

Re-running `mix format` apparently just adds parenthesis around calls ; you can see the effect in this commit https://github.com/etalab/transport-site/pull/2416/commits/e04fb6974fceb8c6ed0bd95b0977143733793c07.

If this is confirmed and my understanding is correct, I wonder if you would consider generating files that are already formatted as expected by `mix format`?

Happy to try contributing a PR if there is an agreement here.

**Comment by whatyouhide** [comment]
Hey @thbar! Thanks for reporting. First of all, cool use case, thanks for taking the time to write down some details 😊 

I think what's happening here (I didn't investigate) is that `field` and other macros are in `:locals_without_parens` here in this repository's `.formatter.exs`. However, your repository doesn't specify anything like that in [its `.formatter.exs`](https://github.com/etalab/transport-site/blob/master/.formatter.exs) (rightly so).

To fix this for now, you can add `import_deps` to your `.formatter.exs`:

```elixir
[
  # ...,
  import_deps: [:protobuf]
]
```

since we do _export_ the configuration for library users.

As for the long-term solution, I’m thinking we might want to drop the custom configuration in order to avoid burdening users with having to configure the formatter properly. Thoughts @britto @ericmj?

**Comment by thbar** [comment]
@whatyouhide thanks for the feedback! Much appreciated. I will use your fix (I wasn't aware of `import_deps` yet) ; it is not a huge burden of course, more a dev-experience feedback. Happy to help in any way afterwards.

**Comment by wingyplus** [comment]
I hope that this PR https://github.com/elixir-protobuf/protobuf/pull/284 would fix this issue. :)

**Comment by wingyplus** [comment]
I hope that this PR https://github.com/elixir-protobuf/protobuf/pull/284 would fix this issue. :)

**Comment by whatyouhide** [comment]
@thbar can you give this a try in the latest `main` now that #284 has been merged? 🙃

**Comment by thbar** [comment]
@whatyouhide I made a very quick try today, but I believe it has not changed the behaviour.

I used this:

```
mix escript.install git https://github.com/elixir-protobuf/protobuf.git
asdf reshim elixir
protoc --elixir_out=. gtfs-realtime.proto 
```

I see some changes (the protoc gen version) which seems to indicate the tool version is indeed not the same, but the parenthesis are still removed:

```diff
 defmodule TransitRealtime.FeedHeader.Incrementality do
   @moduledoc false
-  use Protobuf, enum: true, protoc_gen_elixir_version: "0.10.0", syntax: :proto2
+  use Protobuf, enum: true, protoc_gen_elixir_version: "0.10.1-dev", syntax: :proto2
 
-  field(:FULL_DATASET, 0)
-  field(:DIFFERENTIAL, 1)
+  field :FULL_DATASET, 0
+  field :DIFFERENTIAL, 1
 end
```

I'll look closer when I have a bit of time, but wanted to provided some early feedback.

**Comment by wingyplus** [comment]
When generating proto code, the code with format with option defined in https://github.com/elixir-protobuf/protobuf/blob/main/lib/protobuf/protoc/generator/util.ex#L6. So it'll not care `.formatter.exs` for sure. 

I've been try the solution that @ericmj suggested in #284 in https://github.com/wingyplus/protobuf/commit/990ec8511ddb695b74ccd186eccf94c31ce90c3d. It's look work pretty well when the project doesn't have `import_deps` in the `.formatter.exs`. But it'll raise an error below when I add `:protobuf` to `import_deps`:

```
** (Mix.Error) Unknown dependency :protobuf given to :import_deps in the formatter configuration. The dependency is not listed in your mix.exs for environment :dev
    (mix 1.13.4) lib/mix.ex:515: Mix.raise/2
    (mix 1.13.4) lib/mix/tasks/format.ex:353: anonymous fn/3 in Mix.Tasks.Format.eval_deps_opts/2
    (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix 1.13.4) lib/mix/tasks/format.ex:352: Mix.Tasks.Format.eval_deps_opts/2
    (mix 1.13.4) lib/mix/tasks/format.ex:308: anonymous fn/5 in Mix.Tasks.Format.eval_deps_and_subdirectories/4
    (mix 1.13.4) lib/mix/tasks/format.ex:221: Mix.Tasks.Format.formatter_for_file/2
    (protobuf 0.10.1-dev) lib/protobuf/protoc/generator/util.ex:90: Protobuf.Protoc.Generator.Util.format/2
    (protobuf 0.10.1-dev) lib/protobuf/protoc/generator.ex:36: Protobuf.Protoc.Generator.generate/2
```

I'm not sure why. :(

**Comment by ericmj** [comment]
@wingyplus I think it's because the escript protoc plugin is not running in the context of your mix project so the `mix.exs` file and project needs to be loaded for it to work. I am not sure if that's possible but worth looking into.

**Comment by whatyouhide** [comment]
I investigated this a bit. My conclusion here is this: these files are autogenerated by the Protobuf library, so I don't think you should be formatting them with your `mix format` pass. I think you should exclude them.

To me, it's analogous to having Credo run on these autogenerated files: you wouldn't do that, because your Credo config could not align with how the maintainers of the Protobuf library work and generate the files. So, I think running Protobuf's own formatter on the generated files so that they're consistent is the right approach here.

Thank you everyone for the discussion! 💟

**Comment by thbar** [comment]
@whatyouhide thanks for investigating! Overall I like your conclusion: it can be complicated to control the exact format etc anyway.

Thanks everyone for the discussion as well, we'll just skip the relevant files. Thanks!
